version: '3'
services:
  ouroboros:
    image: pyouroboros/ouroboros
    deploy:
      mode: global
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb
      - TZ=America/Edmonton
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
